# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
#disqus: dbyll
#google_analytics: dbyll
title: Invente 

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Invente 

description: Sharing Blog 
author:
  name: Silvio Greuel
  email: silvio.greuel@inventti.com.br 
  github: inventti-silvio 
  twitter: silviogreuel 
  #pinterest: silviogreuel 
  linkedin: silviogreuel
  bio: TOW!
  profile: https://pbs.twimg.com/profile_images/2884969533/184e6ef83285fe8d09c579869240f3bd_400x400.jpeg 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

sidebar_background_image: http://apod.nasa.gov/apod/image/1312/horsehead_chumack_1800.jpg

BASE_PATH:

gems:
  - jekyll-paginate
